name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install
        run: npm ci
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - name: package
        run: npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: vscode-tree-extension
          path: '*.vsix'